ws got just plain fancier

diff --git a/bin/ws b/bin/ws
--- a/bin/ws
+++ b/bin/ws
@@ -3,8 +3,9 @@
 gw=0
 gc=0
 gl=0
+#  if they exist, make them refresh
 for s in `vim --serverlist`; do
-    case $s in 
+    case $s in
         WKLY) vim --servername WKLY --remote-send ':source ~/.vim/weekly.vim<CR><CR>'
               gw=1
               ;;
@@ -17,7 +18,48 @@ for s in `vim --serverlist`; do
         ?) ;;
     esac
 done
-
+#  values:  1 = weekly       gw
+#           2 = sacalh       gc
+#           4 = snls         gl
+#  $1 = 7  create all three
+#  $1 = 6  create sacalh and snls
+#  $1 = 5  create weekly and snls
+#  $1 = 4  create snls
+#  $1 = 3  create weekly and sacalh
+#  $1 = 2  create sacalh
+#  $1 = 1  create weekly
+if test $# -lt 1 || test $1 -eq 7; then
+    fm=7
+else
+    case $1 in
+        6) gw=1
+           ;;
+        5) gc=1
+           ;;
+        4) gw=1
+           gc=1
+           ;;
+        3) gl=1
+           ;;
+        2) gw=1
+           gl=1
+           ;;
+        1) gc=1
+           gl=1
+           ;;
+        ?) echo 'cannot understand $1: ' $1
+           echo 'it is optional'
+           echo 'it can be 1 - 7 if it exists'
+           echo '(1) creates weekly'
+           echo '(2) creates sacalh'
+           echo '(3) creates weekly and sacalh'
+           echo '(4) creates snls (laundry)'
+           echo '(5) creates weekly and snls'
+           echo '(6) creates sacalh and snls'
+           echo '(7) creates weekly, sacalh, and snls'
+           exit 1
+    esac
+fi
 if test $gw -eq 0; then
     weekly
 fi
@@ -29,4 +71,3 @@ fi
 if test $gl -eq 0; then
     snls
 fi
-    
